### PR TITLE
feat(widget-chat): storage adapter local storage

### PR DESCRIPTION
**Pull request by adamweeks**

### CODE REVIEW

**Comment by adamweeks** [comment]
@ianwremmel was there anything else I needed to do for the device registration storage?

**Comment by ianwremmel** [comment]
nope; that should do it. might want to look into why the test is failing though. seems likely to be unrelated, but let's try to get the dev branch fixed as soon as possible.

**Comment by adamweeks** [comment]
Yea, I noticed the activity list tests are failing but @bzang has a PR #216 that changes how it all works so I left it alone.

**Comment by ianwremmel** [comment]
fair enough

**Pull request merged**
